Repository Natoman95/ZB-NG-Senior-Project, pull requests merged in 2018-04, with the labels that each got.

#121 Slight change to installation instructions
  README.md
Labels: Documentation

#131 Post-Not-Working
  goco-transit/src/services/http-service.js
Labels: Bug

#138 Link to Hand-Off Documentation
  README.md
Labels: Documentation

#140 66-UI-inconsistencies
  goco-transit/src/pages/search-page.js
  goco-transit/src/pages/settings-page.js
Labels: Client, Revision

#161 Added driver note to add request dialog
  goco-transit/package.json
  goco-transit/src/components/dialog-boxes/add-request-dialog.js
Labels: Client, Revision

#160 Fixed datetime method
  goco-transit/src/pages/passenger-page.js
  goco-transit/src/services/date-service.js
Labels: Bug, Client

#162 66 ui inconsistencies
  goco-transit/src/components/dialog-boxes/add-request-dialog.js
  goco-transit/src/pages/driver-page.js
  goco-transit/src/pages/passenger-page.js
  goco-transit/src/services/request-service.js
  goco-transit/src/services/ride-service.js
Labels: Bug, Client, Server

#163 Fixing more stuff (the phone)
  goco-transit/src/pages/settings-page.js
Labels: Bug, Client
