Repository Natoman95/ZB-NG-Senior-Project, pull requests merged in 2018-02, with the labels that each got.

#47 5-Login Page
  goco-transit/.env
  goco-transit/package-lock.json
  goco-transit/package.json
  goco-transit/src/App.js
  goco-transit/src/client.js
  goco-transit/src/components/login.js
  goco-transit/src/components/offers.js
  goco-transit/src/components/request-search.js
  goco-transit/src/components/requests.js
  goco-transit/src/components/settings.js
  goco-transit/src/images/gordon_360_home.png
  goco-transit/src/services/auth-service.js
  goco-transit/src/services/http-service.js
  goco-transit/src/services/storage-service.js
  goco-transit/yarn.lock
Labels: Client, enhancement

#52 50-Rename Components
  goco-transit/src/App.js
  goco-transit/src/pages/login-page.js
  goco-transit/src/pages/main-page.js
  goco-transit/src/pages/offers-page.js
  goco-transit/src/pages/request-search-page.js
  goco-transit/src/pages/requests-page.js
  goco-transit/src/pages/settings-page.js
Labels: Client, enhancement

#51 Readme Update
  README.md
Labels: Documentation

#54 45-Auto-Generate all Lists from a JS List Object
  goco-transit/src/models/request-model.js
  goco-transit/src/models/ride-model.js
  goco-transit/src/models/user-model.js
  goco-transit/src/pages/offers-page.js
  goco-transit/src/pages/request-search-page.js
  goco-transit/src/pages/requests-page.js
  goco-transit/src/services/auth-service.js
  goco-transit/src/services/ride-service.js
  goco-transit/src/services/user-service.js
Labels: Client, enhancement

#61 48-Allow user to Login with "enter" key
  goco-transit/src/pages/login-page.js
Labels: Client, Enhancement

#71 18-Make AppBar Sticky
  goco-transit/src/pages/main-page.js
  goco-transit/src/services/ride-service.js
Labels: Bug, Client

#74 73-Rename page links
  goco-transit/src/pages/driver-page.js
  goco-transit/src/pages/main-page.js
  goco-transit/src/pages/passenger-page.js
  goco-transit/src/pages/search-page.js
Labels: Chore, Client

#76 Icons and Create React App Documentation
  README.md
Labels: Documentation

#78 77-Switch to Create React App
  .gitignore
  goco-transit/.env
  goco-transit/.gitignore
  goco-transit/package-lock.json
  goco-transit/package.json
  goco-transit/public/index.html
  goco-transit/public/manifest.json
  goco-transit/public/robots.txt
  goco-transit/src/App.css
  goco-transit/src/App.js
  goco-transit/src/App.test.js
  goco-transit/src/client.js
  goco-transit/src/components/add-offer-dialog.js
  goco-transit/src/components/add-request-dialog.js
  goco-transit/src/components/delete-offer-dialog.js
  goco-transit/src/components/delete-request-dialog.js
  goco-transit/src/components/delete-ride-dialog.js
  goco-transit/src/icon-library.js
  goco-transit/src/index.css
  goco-transit/src/index.js
  goco-transit/src/pages/driver-page.js
  goco-transit/src/pages/passenger-page.js
  goco-transit/src/pages/search-page.js
  goco-transit/src/registerServiceWorker.js
  goco-transit/src/server.js
  goco-transit/src/services/auth-service.js
  goco-transit/src/services/http-service.js
  goco-transit/src/theme.js
  goco-transit/yarn.lock
Labels: Client, Enhancement
